/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cg;

public class MyLinkedList {
	public static void main(String[] args) {
		System.out.println("Welcome !");
	}
}
