/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cg;

public class MyLinkedList<K> {
	private AllNode head;
	private AllNode tail;

	public MyLinkedList(AllNode head, AllNode tail) {
		this.head = head;
		this.tail = tail;
	}
}